### ISSUE TITLE
Request for Grade

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/animal-rescue-website#1]
Hey @charlie-quinn!

It's finally the end of the semester; crazy where the time goes.

So here's my website, which was influenced by the existing one here (https://www.furry-tales.ca/#/).

In general, I did my best to satisfy Markbot's requirements, whilst also bringing in some of the skills we learned this semester (including some more interesting applications of SVG's in hover states). My favicons and my images are compressed correctly, although I could probably still up the quality of some of the images without affect performance atrociously. The site isn't particularly creative, and it's not crazy-heavy on content either. The upside to that is my code has stayed reasonably well-organized and intuitive, but is definitely a little on the bland side. Overall, it is reasonably responsive and accessible (although you could definitely argue that point against the pink I sampled from the original website.)

Overall, I'm pretty confident I understand everything covered this semester, and how it ties into everything we've learned previously. I'd probably give myself a B on this site? B+ if you feel generous? It works, but it's not awe-inspiring.

I know I wasn't in class a lot this semester, but I hope you know our class really enjoyed having you as a prof. Thanks for all your hard work. Have a great holidays!

MacKenzie Bulkowski-Rose

**Comment by charlie-quinn** [comment]
Thanks for the kind words, MacKenzie! I've really enjoyed coming to class for your group. 😄 

✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your gmail address.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
