### ISSUE TITLE
Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/animal-rescue-website#2]
Hi @charlie-quinn!

I completed most of the testing; I left some elements unchecked because although they were tested, the errors found weren't fixed in the site. (Testing took a lot longer than I thought it would! Lesson learned: don't treat accessibility like an after-thought.)

I also couldn't figure out how to edit the actual sheets, so I'm attaching photos of my testing sheets. My apologies about that.

Cheers!

MacKenzie Bulkowski-Rose

![testing-1](https://user-images.githubusercontent.com/19557909/70752899-95958b80-1d01-11ea-89aa-2695993ff6c1.jpg)
![testing-2](https://user-images.githubusercontent.com/19557909/70752901-95958b80-1d01-11ea-88fa-e00c11bd76b1.jpg)

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`
